version: '3.8'

services:
  factonetdb:
    image: postgres:15
    restart: always
    ports:
      - "5434:5432"
    environment:
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: FactonetDB
    container_name: factonetdb
    volumes:
      - ./database:/var/lib/postgresql/data